# This is the docker image that is used. 
image: ezzieyguywuf/mycad_devel

stages:
    - pages

pages:
    stage: pages
    script:
        - doxygen doc/Doxyfile
        - mv doc/doxygen/html/ public/
    artifacts:
        paths:
            - public
    only:
        - pages
