# This is the docker image that is used. 
image: mszg/docker-ubuntu-dev

stages:
    - build
    - test
    - pages

build:
    stage: build
    script:
        - mkdir -p build
        - cd build
        - cmake ..
        - make -j4 all
    artifacts:
        paths:
            - ./build
    only:
        - master

test:
    stage: test
    script:
        - ./build/bin/MyCAD_Tests
    only:
        - master

pages:
    stage: pages
    script:
        - doxygen doc/Doxyfile
        - mv doc/doxygen/html/ public/
    artifacts:
        paths:
            - public
    only:
        - master
