name:                opengl-haskell
version:             0.1.0.0
github:              "githubuser/opengl-haskell"
license:             BSD3
author:              "Wolfgang E. Sanyer"
maintainer:          "WolfgangESanyer@Gmail.com"
copyright:           "2020 Wolfgang E. Sanyer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/opengl-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- GLFW-b
- gl
- JuicyPixels
- linear
- vector

library:
  source-dirs: src

executables:
  opengl-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opengl-haskell

tests:
  opengl-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opengl-haskell
