name:                Entity
version:             0.1.0.0
github:              "githubuser/Entity"
license:             MPL-2.0
author:              "Wolfgang E. Sanyer"
maintainer:          "WolfgangESanyer@Gmail.com"
copyright:           "2020 Wolfgang E. Sanyer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HaskellCAD#readme>

dependencies:
- base >= 4.7 && < 5
- Geometry
- Topology
- prettyprinter
- mtl

library:
  source-dirs: src
  exposed-modules:
      - Entity

tests:
  HaskellCAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Entity
    - hspec
