name:                MyCAD
version:             0.1.0.0
github:              "githubuser/mycad"
license:             BSD3
author:              "Wolfgang E. Sanyer"
maintainer:          "WolfgangESanyer@Gmail.com"
copyright:           "2020 Wolfgang E. Sanyer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/opengl-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- linear
- mtl
- containers
- haskeline
- Entity
- Geometry
- Topology
- text

executables:
  mycad-tui:
    main: MyCAD_Tui.hs
    source-dirs: app
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
    other-modules:
        - TUI.CommandParser
        - TUI.CommandRunner
        - TUI.Errors
        - TUI.LaunchTUI
        - Paths_MyCAD

  mycad-gui:
    main: MyCAD_gui.hs
    source-dirs: app
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
    dependencies:
        - GLFW-b
        - gl
        - ansi-terminal
        - JuicyPixels
        - vector
        - stm
        - filepath
    other-modules:
        - GUI.GL.Helpers
        - GUI.GL.Primitives
        - GUI.GL.RenderData
        - GUI.GL.Renderer
        - GUI.GL.Pictures
        - GUI.LaunchGUI
        - GUI.GLFW_Helpers
        - GUI.GraphicData
        - GUI.RenderQueue
        - GUI.ViewSpace
        - Paths_MyCAD

  mycad:
    main: MyCAD.hs
    source-dirs: app
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
    dependencies:
        - GLFW-b
        - gl
        - ansi-terminal
        - JuicyPixels
        - vector
        - stm
        - filepath
    other-modules:
        - GUI.GL.Helpers
        - GUI.GL.Primitives
        - GUI.GL.RenderData
        - GUI.GL.Renderer
        - GUI.GL.Pictures
        - GUI.LaunchGUI
        - GUI.GLFW_Helpers
        - GUI.GraphicData
        - GUI.RenderQueue
        - GUI.ViewSpace
        - TUI.CommandParser
        - TUI.CommandRunner
        - TUI.Errors
        - TUI.LaunchTUI
        - Paths_MyCAD
