name:                MyCAD
version:             0.1.0.0
github:              "githubuser/mycad"
license:             BSD3
author:              "Wolfgang E. Sanyer"
maintainer:          "WolfgangESanyer@Gmail.com"
copyright:           "2020 Wolfgang E. Sanyer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/opengl-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- linear
- mtl

executables:
  MyCAD-exe:
    main: Main.hs
    source-dirs: MyCAD
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  gui-exe:
    main: Main.hs
    source-dirs: GUI
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GLFW-b
    - gl
    - ansi-terminal
    - JuicyPixels
    - vector
    - stm

  tui-exe:
    main: Main.hs
    source-dirs: TUI
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskeline
    - Entity
    - Geometry
    - Topology
    - containers
    - text
